# Generated by Django 5.2.5 on 2025-08-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./product/images/brand_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./product/images/category_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aerialImage',
            field=models.ImageField(blank=True, null=True, upload_to='./product/images/aerial_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='backImage',
            field=models.ImageField(blank=True, null=True, upload_to='./product/images/back_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='frontImage',
            field=models.ImageField(blank=True, null=True, upload_to='./product/images/front_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='sideImage',
            field=models.ImageField(blank=True, null=True, upload_to='./product/images/side_images/'),
        ),
    ]
