# Generated by Django 5.2.5 on 2025-08-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
