# Generated by Django 5.2.5 on 2025-09-28 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_shop_options_order_deliverer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, help_text='All colors available for this product', related_name='products', to='product.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, help_text='All sizes available for this product', related_name='products', to='product.size'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Associate image with a specific color (applies to all sizes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.color'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary image for this product/variant/color combination'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this specific size/color combination', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available quantity for this variant')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit - unique identifier for this variant', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional notes for this specific variant', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this variant is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='product.size')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product__name', 'size__size_type', 'size__numeric_size', 'size__alpha_size', 'color__color_name'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.productvariant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.productvariant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Associate image with a specific product variant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='review',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Review for specific variant (size/color combination)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'variant')},
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
    ]
