# Generated by Django 5.2.5 on 2025-08-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_size_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name', 'size', 'price'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
    ]
