# Generated by Django 5.2.5 on 2025-10-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productsize_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_images',
            field=models.ManyToManyField(blank=True, help_text='All images associated with this product', related_name='products', to='product.productimage'),
        ),
    ]
