# Generated by Django 5.2.5 on 2025-08-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_size_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['size', 'price', 'name'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
    ]
