# Generated by Django 5.2.5 on 2025-08-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_size_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['hex_code'], 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['size', 'productName', 'price'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='productName',
        ),
    ]
