# Generated by Django 5.2.5 on 2025-10-09 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_order_delivery_option_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Primary image for this specific variant (overrides product images)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='product.productimage'),
        ),
    ]
