# Generated by Django 5.2.5 on 2025-10-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productimage_variant_productvariant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='image',
            new_name='images',
        ),
    ]
