# Generated by Django 5.2.5 on 2025-10-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_image_productvariant_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Associate image with a specific product variant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productvariant'),
        ),
    ]
