# Generated by Django 5.2.5 on 2025-10-13 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productvariant_images_productimage_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_images',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Image specific to this size/color variant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_products', to='product.productimage'),
        ),
    ]
