# Generated by Django 5.2.5 on 2025-08-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('manager', 'Manager')], default='client', max_length=20),
        ),
    ]
