# Generated by Django 5.2.5 on 2025-08-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('Buyer', 'Buyer'), ('seller', 'Seller'), ('deliverer', 'Deliverer')], default='client', max_length=20),
        ),
    ]
